version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: xclone_dev
      POSTGRES_USER: wallison
      POSTGRES_PASSWORD: 135543223432
    ports:
      - "5432:5432"
